repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^env/
    -   id: end-of-file-fixer
        exclude: ^env/
    -   id: check-yaml
        exclude: ^env/
    -   id: debug-statements
        exclude: ^env/
-   repo: https://github.com/psf/black
    rev: '22.6.0'
    hooks:
    -   id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.8
        exclude: ^env/
    -   id: black-jupyter
        language_version: python3.8
        exclude: ^env/
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    -   id: setup-cfg-fmt
        exclude: ^env/
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/|env/)
        args: [--py37-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
        exclude: ^env/
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    -   id: pyupgrade
        exclude: ^env/
        args: [--py37-plus]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^(env/|$/migrations/)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
